config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get '/s(/:code)', to: 'access#grant_access', as: 'share'

  resources :rooms do
    resources :sharing_codes, only: [:index, :new, :show, :create, :destroy]
  end

end

app/models/sharing_code.rb
class SharingCode < ActiveRecord::Base
  belongs_to :room
  belongs_to :user

  before_save :default_values

  def expired?
    expires && Time.now > expiry_date
  end

  def default_values
    # Generate a random 12-digit alphanumeric string
    self.code = "#{room.id.to_s(36)}#{SecureRandom.random_number(36**12).to_s(36)}"

    self.expiry_date ||= Time.now.advance(hours: +1)
    self.expires ||= false

    true
  end
end

app/controllers/sharing_codes_controller.rb
class SharingCodesController < ApplicationController
  after_action :verify_authorized

  expose(:room)
  expose(:sharing_code, attributes: :sharing_code_params)
  expose(:sharing_codes, ancestor: :room)
  expose(:accessible_codes) { sharing_codes.select { |c| !c.expired? } }

  def index
    authorize room, :update?

    respond_to do |format|
      format.js
    end
  end

  def show
    authorize sharing_code

    respond_to do |format|
      format.js
    end
  end

  def new
    authorize sharing_code

    respond_to do |format|
      format.js
    end
  end

  def create
    authorize sharing_code

    respond_to do |format|
      if sharing_code.save
        format.js { render :show }
      else
        format.json { render json: sharing_code.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize sharing_code

    sharing_code.destroy

    respond_to do |format|
      format.js { render :index }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def sharing_code_params
      params.permit :expires, :expiry_date
    end

end

app/views/sharing_codes/_index_modal.html.erb
<div id="index-modal" class="ui modal">
  <i class="close icon"></i>
  <div class="header">
    <%= t('sharing.manage_sharing') %>
  </div>
  <div class="content">
    <div class="ui top attached tabular menu">
      <a class="active item">
        <%= t('sharing.codes') %>
      </a>
    </div>
    <div class="ui bottom attached active tab segment">
      <div class="ui middle aligned divided list">
        <% codes.each do |code| %>
        <div class="item">
          <div class="right floated content">
            <%= render partial: 'common/facebook_share', locals: { url: share_url(code.code), title: code.room.name } %>
            <%= render partial: 'common/twitter_share', locals: { url: share_url(code.code), title: code.room.name } %>
            <%= render partial: 'common/google_plus_share', locals: { url: share_url(code.code) } %>
            <div class="ui circular icon button"
                 onClick="window.prompt('<%= t('sharing.clipboard_message') %>', '<%= share_url code.code %>');">
              <i class="copy icon"></i>
            </div>
            <%= link_to room_sharing_code_path(room_id: code.room.id, id: code.id), remote: true, method: :delete, class: "ui basic compact red button" do %>
                <%= t('sharing.revoke') %>
            <% end %>
          </div>
          <i class="key icon"></i>
          <div class="content">
            <div class="header">
              <%= code.code %>
            </div>
            <div class="description">
              <% if code.expires %>
                Expires in <%= distance_of_time_in_words Time.now, code.expiry_date %>
              <% else %>
                Never expires.
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="actions">
    <div class="ui ok button">
      <%= t('sharing.done_button') %>
    </div>
  </div>
</div>

app/views/sharing_codes/_new_modal.html.erb
<div id="new-modal" class="ui small modal">
  <i class="close icon"></i>
  <div class="header">
    <%= t('sharing.new_sharing_code') %>
  </div>
  <div class="content">
    <%= form_tag room_sharing_codes_path, id: 'new-sharing-form', method: 'post', remote: true, class: 'ui form' do %>
      <div class="inline field">
        <div class="ui toggle checkbox">
          <%= check_box_tag :expires, 1, false %>
          <%= label_tag :expires %>
        </div>
      </div>
      <div class="inline fields">
        <%= label_tag :expiry_date, 'Expires In' %>
        <div class="field">
          <div class="ui radio checkbox">
            <%= radio_button_tag :expiry_date, Time.now.advance(hours: +1), checked: true %>
            <%= label_tag :expiry_date, t('sharing.one_hour') %>
          </div>
        </div>
        <div class="field">
          <div class="ui radio checkbox">
            <%= radio_button_tag :expiry_date, Time.now.advance(days: +1) %>
            <%= label_tag :expiry_date, t('sharing.one_day') %>
          </div>
        </div>
        <div class="field">
          <div class="ui radio checkbox">
            <%= radio_button_tag :expiry_date, Time.now.advance(weeks: +1) %>
            <%= label_tag :expiry_date, t('sharing.one_week') %>
          </div>
        </div>
        <div class="field">
          <div class="ui radio checkbox">
            <%= radio_button_tag :expiry_date, Time.now.advance(months: +1) %>
            <%= label_tag :expiry_date, t('sharing.one_month') %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <div class="ui ok basic orange icon button" onclick="$('#new-sharing-form').submit();">
      <i class="plus icon"></i>
      <%= t('sharing.create_button') %>
    </div>
  </div>
</div>

app/views/sharing_codes/_show_modal.html.erb
<div id="show-modal" class="ui small modal">
  <i class="close icon"></i>
  <div class="header">
    <%= t('sharing.sharing_code') %>
  </div>
  <div class="content">
    <h4 class="ui horizontal divider header">
      <%= sharing_code.code %>
    </h4>
    <%= render partial: 'common/facebook_share', locals: { url: share_url(sharing_code.code), title: sharing_code.room.name } %>
    <%= render partial: 'common/twitter_share', locals: { url: share_url(sharing_code.code), title: sharing_code.room.name } %>
    <%= render partial: 'common/google_plus_share', locals: { url: share_url(sharing_code.code) } %>
    <div class="ui circular icon button"
         onClick="window.prompt('<%= t('sharing.clipboard_message') %>', '<%= share_url sharing_code.code %>');">
      <i class="copy icon"></i>
    </div>
  </div>
  <div class="actions">
    <div class="ui ok basic button">
      <%= t('common.ok') %>
    </div>
  </div>
</div>

app/views/sharing_codes/index.js.erb
$("#modal").html("<%= escape_javascript(render partial: 'sharing_codes/index_modal', locals: { codes: accessible_codes } ) %>");
$('#index-modal').modal('show');

app/views/sharing_codes/new.js.erb
$("#modal").html("<%= escape_javascript(render partial: 'sharing_codes/new_modal', locals: { sharing_code: sharing_code } ) %>");
$('#new-modal').modal('show');
$('.ui.checkbox').checkbox();

app/views/sharing_codes/show.js.erb
$("#modal").html("<%= escape_javascript(render partial: 'sharing_codes/show_modal', locals: { sharing_code: sharing_code } ) %>");
$('#show-modal').modal('show');