config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get '/s(/:code)', to: 'access#grant_access', as: 'share'

  resources :rooms do
    resources :sharing_codes, only: [:index, :new, :show, :create, :destroy]
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  resourcify

  # Callbacks
  after_destroy :delete_firebase_entries
  before_save :default_values

  # Validations
  validates :name, presence: true

  has_many :sharing_codes

  def owners
    User.with_role :owner, self
  end

  def users_with_access
    User.with_role :access, self
  end

  def identicon_hash
    Digest::MD5.hexdigest("#{id} - #{name}")
  end

  private

  def delete_firebase_entries
    FirebaseService.delete_room self
    FirebaseService.delete_chat self
  end

  def default_values
    self.sync_id  ||= SecureRandom.uuid
    self.chat_id  ||= SecureRandom.uuid
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  after_action :verify_authorized, except: [:index]

  expose(:room, attributes: :room_params)

  expose(:firebase_url) { ENV['FIREBASE_URL'] }
  expose(:soundcloud_client_id) { ENV['SOUNDCLOUD_CLIENT_ID'] }
  expose(:current_type) { params[:type] }

  expose(:public_rooms) { Room.where public: true }
  expose(:owner_rooms) { Room.with_role :owner, current_or_guest_user }
  expose(:access_rooms) { Room.with_role :access, current_or_guest_user }

  # GET /rooms
  # GET /rooms.json
  def index
    case current_type
    when 'owner'
      @rooms = owner_rooms
    when 'access'
      @rooms = access_rooms
    else
      @rooms = public_rooms
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    authorize room

    payload = {
      uid: current_or_guest_user.id.to_s,
      userId: current_or_guest_user.id,
      username: current_or_guest_user.username,
      avatar: current_or_guest_user.gravatar_url,
      canUpdateRoom: policy(room).update?,
      canAccessRoom: policy(room).show?,
      canUpdateChat: policy(room).show?,
      canAccessChat: policy(room).show?,
      roomId: room.sync_id,
      chatId: room.chat_id
    }

    @token = FirebaseTokenService.create_token(payload)
  end

  # GET /rooms/new
  def new
    authorize room

    room.share_link = true
  end

  # GET /rooms/1/edit
  def edit
    authorize room
  end

  # POST /rooms
  # POST /rooms.json
  def create
    authorize room

    if room_params[:public]
      authorize room, :create_public?
    end

    respond_to do |format|
      if room.save
        current_or_guest_user.add_role :owner, room

        format.html { redirect_to room, notice: I18n.t('rooms.successfully_created') }
        format.json { render :show, status: :created, location: room }
      else
        format.html { render :new }
        format.json { render json: room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    authorize room

    if room_params[:public]
      authorize room, :create_public?
    end

    respond_to do |format|
      if room.update(room_params)
        format.html { redirect_to room, notice: I18n.t('rooms.successfully_updated') }
        format.json { render :show, status: :ok, location: room }
      else
        format.html { render :edit }
        format.json { render json: room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    authorize room

    room.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: I18n.t('rooms.successfully_destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit :name, :public
    end
end

app/helpers/room_helper.rb
module RoomHelper

  def my_rooms_class(current_type)
    current_type == 'owner' ? 'active orange' : ''
  end

  def shared_rooms_class(current_type)
    current_type == 'access' ? 'active orange' : ''
  end

  def public_rooms_class(current_type)
    current_type != 'access' && current_type != 'owner' ? 'active orange' : ''
  end

end

app/views/rooms/_form.html.erb
<%= form_for room, html: { class: "ui error form segment" } do |f| %>

  <%= error_messages room %>

  <div class="required field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, autocomplete: "off" %>
  </div>

  <% if policy(room).create_public? %>
  <h5 class="ui header"><%= t('rooms.sharing') %></h5>
  <div class="field inline">
    <div class="ui toggle checkbox">
      <%= f.check_box :public %>
      <label><%= t('rooms.public_access') %></label>
    </div>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit class: "ui blue button"%>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h2 class="ui dividing header"><%= t('rooms.edit_room') %></h2>

<%= render 'form' %>

<%= link_to t('common.show'), room , class: "ui button"%>
<%= link_to t('common.back'), :back, class: "ui button" %>

app/views/rooms/index.html.erb
<div class="ui secondary pointing menu">
  <%= link_to rooms_path, class: "#{public_rooms_class current_type} item" do %>
    <%= t('rooms.public_rooms') %>
  <% end %>
  <%= link_to rooms_path(type: :owner), class: "#{my_rooms_class current_type} item" do %>
    <%= t('rooms.my_rooms') %>
  <% end %>
  <%= link_to rooms_path(type: :access), class: "#{shared_rooms_class current_type} item" do %>
    <%= t('rooms.shared_with_me') %>
  <% end %>
  <div class="item right floated">
      <%= link_to t('rooms.new_room'), new_room_path, class: "ui green button" %>
  </div>
</div>

<% if @rooms.empty? %>
<div class="ui segment">
  <div class="header"><%= t('rooms.no_rooms') %></div>
</div><br/>
<% end %>
<div class="ui three cards">
  <% @rooms.each do |room| %>
  <div class="ui card">
    <canvas class="image" width="200" height="200" data-jdenticon-hash="<%= room.identicon_hash %>">
      Fallback text for browsers not supporting canvas
    </canvas>
    <div class="content">
      <%= link_to room, class: "header" do %>
        <%= room.name %>
      <% end %>
      <div class="ui right corner label">
        <% if room.public %>
          <i class="large disabled unhide icon popup" data-content="<%= t('rooms.public_room') %>"></i>
        <% else %>
          <i class="large disabled hide icon popup" data-content="<%= t('rooms.private_room') %>"></i>
        <% end %>
      </div>
    </div>
    <div class="extra content">
      <% if policy(room).update? %>
        <div class="ui two buttons">
          <%= link_to [:edit, room], class: "ui basic blue button" do %>
              Edit
          <% end %>
          <%= link_to room, method: :delete, class: "ui basic red button" do %>
              Delete
          <% end %>
        </div>
      <% else %>
        <div class="right floated author">
          <img class="ui avatar image" src="<%= room.owners.first.gravatar_url %>"> <%= room.owners.first.username %>
        </div>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<h2 class="ui dividing header"><%= t('rooms.new_room') %></h2>

<%= render 'form' %>

<%= link_to t('common.back'), :back, class: "ui button" %>

app/views/rooms/show.html.erb
<h2 class="ui dividing header"><%= room.name %></h2>

<% if policy(room).update? %>
<div class="ui blue top right attached label">
  <div class="ui top right pointing click dropdown">
    <i class="share icon"></i> <%= t('rooms.share') %>
    <div class="menu">
      <%= link_to t('sharing.new_sharing_code'), new_room_sharing_code_path(room.id), remote: true, class: 'item' %>
      <%= link_to t('sharing.manage_sharing'), room_sharing_codes_path(room.id), remote: true, class: 'item' %>
    </div>
  </div>
</div>
<% end %>

<div class="ui two column grid">
  <div class="column">
    <%= react_component('MediaPlayerComponent', firebaseUrl: firebase_url, roomId: room.sync_id,
                        token: @token, canUpdate: policy(room).update?,
                        clientId: soundcloud_client_id) %>
  </div>
  <div class="column">
    <%= react_component('ChatComponent', firebaseUrl: firebase_url, chatId: room.chat_id,
                        token: @token, clientId: soundcloud_client_id,
                        userId: current_or_guest_user.id,
                        username: current_or_guest_user.username,
                        avatar: current_or_guest_user.gravatar_url) %>
  </div>
</div>

<br />

<%= react_component('PresenceComponent', firebaseUrl: firebase_url, roomId: room.sync_id,
                    token: @token, userId: current_or_guest_user.id,
                    username: current_or_guest_user.username,
                    avatar: current_or_guest_user.gravatar_url) %>

<div id="modal"></div>